import { IResolvers } from "graphql-tools";
const resolverMap: IResolvers = {
  Query: {
    helloWorld(_: void, args: void): string {
      return `Hello GraphQL~!`;
    },
    productConstraintInfos(productCode: string, args: void): Array<Object> {
      return [
        {
          productFamily: "Allplex",
          productCode: "PRODUCT_ALL_001",
          productId: 10001,
          productGroup: "00010",
          orderSequence: "001",
          extractionSerialNumber: "UC96, EX11",
          extractionFamily: "PRODUCT_EXT_001, PRODUCT_EXT_012",
          extractionProtocol: "1, 1",
          samplePremix: "1",
          pcrProductSerialNumber1: "RP03",
          pcrProductSerialNumber2: "RP26",
          icName: "RP-V IC",
          pcrTubeInterval: 0,
          pcrReconstruct: 1,
          plateTutorial: 0,
          icUse: "F",
          urineCombination: "F",
          inputDwpBarcode: "F",
          inputPlateBarcode: "F",
          pcCount: 1,
          ncCount: 1,
          sdCount: 0,
          wtcCount: 0,
          panelCount: 1,
          pcrsetupBarcode: "T",
          maxSumCount: 96,
        },
        {
          productFamily: "Allplex",
          productCode: "PRODUCT_ALL_002",
          productId: 10002,
          productGroup: "00010",
          orderSequence: "001",
          extractionSerialNumber: "UC96, EX11",
          extractionFamily: "PRODUCT_EXT_001, PRODUCT_EXT_012",
          extractionProtocol: "1, 1",
          samplePremix: "1",
          pcrProductSerialNumber1: "RP03",
          pcrProductSerialNumber2: "RP26",
          icName: "RP-V IC",
          pcrTubeInterval: 0,
          pcrReconstruct: 1,
          plateTutorial: 0,
          icUse: "F",
          urineCombination: "F",
          inputDwpBarcode: "F",
          inputPlateBarcode: "F",
          pcCount: 1,
          ncCount: 1,
          sdCount: 0,
          wtcCount: 0,
          panelCount: 1,
          pcrsetupBarcode: "T",
          maxSumCount: 96,
        },
      ];
    },
    productInfos(parent: void, args: any, context: void): Array<Object> {
      console.log("parent:", parent);
      console.log("args:", args);
      console.log("context:", context);
      if (args?.id === 1) {
        return [
          {
            id: 1,
            version: null,
            productCode: "PRODUCT_ALL_001",
            productFamilyId: 1,
            productName: "RP1",
            productAbbreviation: "RP1",
            productDisplayName: "Allplex™ Respiratory Panel 1",
            productFlag: "Overseas",
            nimbusEnable: "T",
            starletEnable: "T",
            vcmsEnable: "F",
            manualEnable: "T",
            mastermixCode: "SP001",
            protocolName: "Allplex Respiratory Panel",
            protocolDesc: "Default",
            protocolExt_1Name: null,
            protocolExt_1Desc: null,
            wtcName: null,
            productId: null,
            releaseDate: null,
            installDatetime: null,
            jsonString: null,
          },
        ];
      }
      return [
        {
          id: 1,
          version: null,
          productCode: "PRODUCT_ALL_001",
          productFamilyId: 1,
          productName: "RP1",
          productAbbreviation: "RP1",
          productDisplayName: "Allplex™ Respiratory Panel 1",
          productFlag: "Overseas",
          nimbusEnable: "T",
          starletEnable: "T",
          vcmsEnable: "F",
          manualEnable: "T",
          mastermixCode: "SP001",
          protocolName: "Allplex Respiratory Panel",
          protocolDesc: "Default",
          protocolExt_1Name: null,
          protocolExt_1Desc: null,
          wtcName: null,
          productId: null,
          releaseDate: null,
          installDatetime: null,
          jsonString: null,
        },
        {
          id: 2,
          version: null,
          productCode: "PRODUCT_ALL_002",
          productFamilyId: 1,
          productName: "RP1",
          productAbbreviation: "RP1",
          productDisplayName: "Allplex™ Respiratory Panel 1",
          productFlag: "Overseas",
          nimbusEnable: "T",
          starletEnable: "T",
          vcmsEnable: "F",
          manualEnable: "T",
          mastermixCode: "SP001",
          protocolName: "Allplex Respiratory Panel",
          protocolDesc: "Default",
          protocolExt_1Name: null,
          protocolExt_1Desc: null,
          wtcName: null,
          productId: null,
          releaseDate: null,
          installDatetime: null,
          jsonString: null,
        },
      ];
    },
  },
};
export default resolverMap;
